---
quorumFlags:
  removeGenesisOnDelete: true

cluster:
  provider: gke  # choose from: local | aws | azure
  cloudNativeServices: false 

gke:
  serviceAccountName: brlparam@brlquorumhyperledger.iam.gserviceaccount.com  # The name of the GKE service account to use
  region: us-central1-c # (Optional) Specify the region for GKE
  projectID: blockchainatasu  # The GCP project ID where GKE is deployed
aws:
  # the aws cli commands uses the name 'quorum-sa' so only change this if you altered the name
  serviceAccountName: quorum-sa
  # the region you are deploying to
  region: ap-southeast-2

azure:
  serviceAccountName: quorum-sa
  # the clientId of the user assigned managed identity created in the template
  identityClientId: azure-clientId
  keyvaultName: azure-keyvault
  # the tenant ID of the key vault
  tenantId: azure-tenantId
  # the subscription ID to use - this needs to be set explicitly when using multi tenancy
  subscriptionId: azure-subscriptionId

# the raw Genesis config
# rawGenesisConfig.blockchain.nodes set the number of validators/signers
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    baseFeePerGas: "0x0"
    nonce: "0x0"
    gasLimit: '0x47b760' 
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'
